//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HairPeaceWebsite.PeaceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Prod", Namespace="http://schemas.datacontract.org/2004/07/HairPeaceService")]
    [System.SerializableAttribute()]
    public partial class Prod : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QtyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string brandField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int inStockField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string prodNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string prodTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int specialField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Image {
            get {
                return this.ImageField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageField, value) != true)) {
                    this.ImageField = value;
                    this.RaisePropertyChanged("Image");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Qty {
            get {
                return this.QtyField;
            }
            set {
                if ((this.QtyField.Equals(value) != true)) {
                    this.QtyField = value;
                    this.RaisePropertyChanged("Qty");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string brand {
            get {
                return this.brandField;
            }
            set {
                if ((object.ReferenceEquals(this.brandField, value) != true)) {
                    this.brandField = value;
                    this.RaisePropertyChanged("brand");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.descriptionField, value) != true)) {
                    this.descriptionField = value;
                    this.RaisePropertyChanged("description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int inStock {
            get {
                return this.inStockField;
            }
            set {
                if ((this.inStockField.Equals(value) != true)) {
                    this.inStockField = value;
                    this.RaisePropertyChanged("inStock");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string prodName {
            get {
                return this.prodNameField;
            }
            set {
                if ((object.ReferenceEquals(this.prodNameField, value) != true)) {
                    this.prodNameField = value;
                    this.RaisePropertyChanged("prodName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string prodType {
            get {
                return this.prodTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.prodTypeField, value) != true)) {
                    this.prodTypeField = value;
                    this.RaisePropertyChanged("prodType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sNumber {
            get {
                return this.sNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.sNumberField, value) != true)) {
                    this.sNumberField = value;
                    this.RaisePropertyChanged("sNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int special {
            get {
                return this.specialField;
            }
            set {
                if ((this.specialField.Equals(value) != true)) {
                    this.specialField = value;
                    this.RaisePropertyChanged("special");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/HairPeaceService")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int activeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string surnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string typeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int active {
            get {
                return this.activeField;
            }
            set {
                if ((this.activeField.Equals(value) != true)) {
                    this.activeField = value;
                    this.RaisePropertyChanged("active");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string pass {
            get {
                return this.passField;
            }
            set {
                if ((object.ReferenceEquals(this.passField, value) != true)) {
                    this.passField = value;
                    this.RaisePropertyChanged("pass");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string surname {
            get {
                return this.surnameField;
            }
            set {
                if ((object.ReferenceEquals(this.surnameField, value) != true)) {
                    this.surnameField = value;
                    this.RaisePropertyChanged("surname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string type {
            get {
                return this.typeField;
            }
            set {
                if ((object.ReferenceEquals(this.typeField, value) != true)) {
                    this.typeField = value;
                    this.RaisePropertyChanged("type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="userCart", Namespace="http://schemas.datacontract.org/2004/07/HairPeaceService")]
    [System.SerializableAttribute()]
    public partial class userCart : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Prod_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int User_IDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Prod_ID {
            get {
                return this.Prod_IDField;
            }
            set {
                if ((this.Prod_IDField.Equals(value) != true)) {
                    this.Prod_IDField = value;
                    this.RaisePropertyChanged("Prod_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int User_ID {
            get {
                return this.User_IDField;
            }
            set {
                if ((this.User_IDField.Equals(value) != true)) {
                    this.User_IDField = value;
                    this.RaisePropertyChanged("User_ID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="bDetails", Namespace="http://schemas.datacontract.org/2004/07/HairPeaceService")]
    [System.SerializableAttribute()]
    public partial class bDetails : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string House_AdressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Order_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProvinceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Street_AdressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SurnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int User_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZIPField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string House_Adress {
            get {
                return this.House_AdressField;
            }
            set {
                if ((object.ReferenceEquals(this.House_AdressField, value) != true)) {
                    this.House_AdressField = value;
                    this.RaisePropertyChanged("House_Adress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Order_ID {
            get {
                return this.Order_IDField;
            }
            set {
                if ((this.Order_IDField.Equals(value) != true)) {
                    this.Order_IDField = value;
                    this.RaisePropertyChanged("Order_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Province {
            get {
                return this.ProvinceField;
            }
            set {
                if ((object.ReferenceEquals(this.ProvinceField, value) != true)) {
                    this.ProvinceField = value;
                    this.RaisePropertyChanged("Province");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Street_Adress {
            get {
                return this.Street_AdressField;
            }
            set {
                if ((object.ReferenceEquals(this.Street_AdressField, value) != true)) {
                    this.Street_AdressField = value;
                    this.RaisePropertyChanged("Street_Adress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Surname {
            get {
                return this.SurnameField;
            }
            set {
                if ((object.ReferenceEquals(this.SurnameField, value) != true)) {
                    this.SurnameField = value;
                    this.RaisePropertyChanged("Surname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int User_ID {
            get {
                return this.User_IDField;
            }
            set {
                if ((this.User_IDField.Equals(value) != true)) {
                    this.User_IDField = value;
                    this.RaisePropertyChanged("User_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ZIP {
            get {
                return this.ZIPField;
            }
            set {
                if ((object.ReferenceEquals(this.ZIPField, value) != true)) {
                    this.ZIPField = value;
                    this.RaisePropertyChanged("ZIP");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="tHistory", Namespace="http://schemas.datacontract.org/2004/07/HairPeaceService")]
    [System.SerializableAttribute()]
    public partial class tHistory : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Order_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Prod_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int purchase_IDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date {
            get {
                return this.DateField;
            }
            set {
                if ((this.DateField.Equals(value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Order_ID {
            get {
                return this.Order_IDField;
            }
            set {
                if ((this.Order_IDField.Equals(value) != true)) {
                    this.Order_IDField = value;
                    this.RaisePropertyChanged("Order_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Prod_ID {
            get {
                return this.Prod_IDField;
            }
            set {
                if ((this.Prod_IDField.Equals(value) != true)) {
                    this.Prod_IDField = value;
                    this.RaisePropertyChanged("Prod_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int purchase_ID {
            get {
                return this.purchase_IDField;
            }
            set {
                if ((this.purchase_IDField.Equals(value) != true)) {
                    this.purchase_IDField = value;
                    this.RaisePropertyChanged("purchase_ID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PTracking", Namespace="http://schemas.datacontract.org/2004/07/HairPeaceService")]
    [System.SerializableAttribute()]
    public partial class PTracking : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int nVisistsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string pageNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int nVisists {
            get {
                return this.nVisistsField;
            }
            set {
                if ((this.nVisistsField.Equals(value) != true)) {
                    this.nVisistsField = value;
                    this.RaisePropertyChanged("nVisists");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string pageName {
            get {
                return this.pageNameField;
            }
            set {
                if ((object.ReferenceEquals(this.pageNameField, value) != true)) {
                    this.pageNameField = value;
                    this.RaisePropertyChanged("pageName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="cLogInDays", Namespace="http://schemas.datacontract.org/2004/07/HairPeaceService")]
    [System.SerializableAttribute()]
    public partial class cLogInDays : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int intNumberOfLoginsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string strDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int intNumberOfLogins {
            get {
                return this.intNumberOfLoginsField;
            }
            set {
                if ((this.intNumberOfLoginsField.Equals(value) != true)) {
                    this.intNumberOfLoginsField = value;
                    this.RaisePropertyChanged("intNumberOfLogins");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strDate {
            get {
                return this.strDateField;
            }
            set {
                if ((object.ReferenceEquals(this.strDateField, value) != true)) {
                    this.strDateField = value;
                    this.RaisePropertyChanged("strDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="order_Attendence", Namespace="http://schemas.datacontract.org/2004/07/HairPeaceService")]
    [System.SerializableAttribute()]
    public partial class order_Attendence : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Order_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Order_ID {
            get {
                return this.Order_IDField;
            }
            set {
                if ((this.Order_IDField.Equals(value) != true)) {
                    this.Order_IDField = value;
                    this.RaisePropertyChanged("Order_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PeaceReference.IHairService")]
    public interface IHairService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHairService/Prod", ReplyAction="http://tempuri.org/IHairService/ProdResponse")]
        bool Prod(string ID, string Name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHairService/Prod", ReplyAction="http://tempuri.org/IHairService/ProdResponse")]
        System.Threading.Tasks.Task<bool> ProdAsync(string ID, string Name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHairService/searchProdID", ReplyAction="http://tempuri.org/IHairService/searchProdIDResponse")]
        int searchProdID(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHairService/searchProdID", ReplyAction="http://tempuri.org/IHairService/searchProdIDResponse")]
        System.Threading.Tasks.Task<int> searchProdIDAsync(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHairService/searchProd", ReplyAction="http://tempuri.org/IHairService/searchProdResponse")]
        int searchProd(string SerialNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHairService/searchProd", ReplyAction="http://tempuri.org/IHairService/searchProdResponse")]
        System.Threading.Tasks.Task<int> searchProdAsync(string SerialNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHairService/GetProd", ReplyAction="http://tempuri.org/IHairService/GetProdResponse")]
        HairPeaceWebsite.PeaceReference.Prod GetProd(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHairService/GetProd", ReplyAction="http://tempuri.org/IHairService/GetProdResponse")]
        System.Threading.Tasks.Task<HairPeaceWebsite.PeaceReference.Prod> GetProdAsync(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHairService/modifyProd", ReplyAction="http://tempuri.org/IHairService/modifyProdResponse")]
        bool modifyProd(HairPeaceWebsite.PeaceReference.Prod product, int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHairService/modifyProd", ReplyAction="http://tempuri.org/IHairService/modifyProdResponse")]
        System.Threading.Tasks.Task<bool> modifyProdAsync(HairPeaceWebsite.PeaceReference.Prod product, int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHairService/newProd", ReplyAction="http://tempuri.org/IHairService/newProdResponse")]
        bool newProd(string ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHairService/newProd", ReplyAction="http://tempuri.org/IHairService/newProdResponse")]
        System.Threading.Tasks.Task<bool> newProdAsync(string ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHairService/appendNewProduct", ReplyAction="http://tempuri.org/IHairService/appendNewProductResponse")]
        bool appendNewProduct(HairPeaceWebsite.PeaceReference.Prod p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHairService/appendNewProduct", ReplyAction="http://tempuri.org/IHairService/appendNewProductResponse")]
        System.Threading.Tasks.Task<bool> appendNewProductAsync(HairPeaceWebsite.PeaceReference.Prod p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHairService/Login", ReplyAction="http://tempuri.org/IHairService/LoginResponse")]
        bool Login(string Email, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHairService/Login", ReplyAction="http://tempuri.org/IHairService/LoginResponse")]
        System.Threading.Tasks.Task<bool> LoginAsync(string Email, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHairService/GetUser", ReplyAction="http://tempuri.org/IHairService/GetUserResponse")]
        HairPeaceWebsite.PeaceReference.User GetUser(string Email, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHairService/GetUser", ReplyAction="http://tempuri.org/IHairService/GetUserResponse")]
        System.Threading.Tasks.Task<HairPeaceWebsite.PeaceReference.User> GetUserAsync(string Email, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHairService/SearchUser", ReplyAction="http://tempuri.org/IHairService/SearchUserResponse")]
        bool SearchUser(string Email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHairService/SearchUser", ReplyAction="http://tempuri.org/IHairService/SearchUserResponse")]
        System.Threading.Tasks.Task<bool> SearchUserAsync(string Email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHairService/GetAnonUser", ReplyAction="http://tempuri.org/IHairService/GetAnonUserResponse")]
        HairPeaceWebsite.PeaceReference.User GetAnonUser(string Email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHairService/GetAnonUser", ReplyAction="http://tempuri.org/IHairService/GetAnonUserResponse")]
        System.Threading.Tasks.Task<HairPeaceWebsite.PeaceReference.User> GetAnonUserAsync(string Email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHairService/editUser", ReplyAction="http://tempuri.org/IHairService/editUserResponse")]
        int editUser(HairPeaceWebsite.PeaceReference.User u, string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHairService/editUser", ReplyAction="http://tempuri.org/IHairService/editUserResponse")]
        System.Threading.Tasks.Task<int> editUserAsync(HairPeaceWebsite.PeaceReference.User u, string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHairService/Registered", ReplyAction="http://tempuri.org/IHairService/RegisteredResponse")]
        bool Registered(string Email, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHairService/Registered", ReplyAction="http://tempuri.org/IHairService/RegisteredResponse")]
        System.Threading.Tasks.Task<bool> RegisteredAsync(string Email, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHairService/Register", ReplyAction="http://tempuri.org/IHairService/RegisterResponse")]
        int Register(HairPeaceWebsite.PeaceReference.User u);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHairService/Register", ReplyAction="http://tempuri.org/IHairService/RegisterResponse")]
        System.Threading.Tasks.Task<int> RegisterAsync(HairPeaceWebsite.PeaceReference.User u);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHairService/prodList", ReplyAction="http://tempuri.org/IHairService/prodListResponse")]
        HairPeaceWebsite.PeaceReference.Prod[] prodList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHairService/prodList", ReplyAction="http://tempuri.org/IHairService/prodListResponse")]
        System.Threading.Tasks.Task<HairPeaceWebsite.PeaceReference.Prod[]> prodListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHairService/fillBySpecial", ReplyAction="http://tempuri.org/IHairService/fillBySpecialResponse")]
        HairPeaceWebsite.PeaceReference.Prod[] fillBySpecial();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHairService/fillBySpecial", ReplyAction="http://tempuri.org/IHairService/fillBySpecialResponse")]
        System.Threading.Tasks.Task<HairPeaceWebsite.PeaceReference.Prod[]> fillBySpecialAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHairService/fillByProdType", ReplyAction="http://tempuri.org/IHairService/fillByProdTypeResponse")]
        HairPeaceWebsite.PeaceReference.Prod[] fillByProdType(string type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHairService/fillByProdType", ReplyAction="http://tempuri.org/IHairService/fillByProdTypeResponse")]
        System.Threading.Tasks.Task<HairPeaceWebsite.PeaceReference.Prod[]> fillByProdTypeAsync(string type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHairService/fillByPrice", ReplyAction="http://tempuri.org/IHairService/fillByPriceResponse")]
        HairPeaceWebsite.PeaceReference.Prod[] fillByPrice(int n);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHairService/fillByPrice", ReplyAction="http://tempuri.org/IHairService/fillByPriceResponse")]
        System.Threading.Tasks.Task<HairPeaceWebsite.PeaceReference.Prod[]> fillByPriceAsync(int n);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHairService/fillByBrand", ReplyAction="http://tempuri.org/IHairService/fillByBrandResponse")]
        HairPeaceWebsite.PeaceReference.Prod[] fillByBrand(string bName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHairService/fillByBrand", ReplyAction="http://tempuri.org/IHairService/fillByBrandResponse")]
        System.Threading.Tasks.Task<HairPeaceWebsite.PeaceReference.Prod[]> fillByBrandAsync(string bName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHairService/htmlBrandFilter", ReplyAction="http://tempuri.org/IHairService/htmlBrandFilterResponse")]
        string[] htmlBrandFilter();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHairService/htmlBrandFilter", ReplyAction="http://tempuri.org/IHairService/htmlBrandFilterResponse")]
        System.Threading.Tasks.Task<string[]> htmlBrandFilterAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHairService/GetCarts", ReplyAction="http://tempuri.org/IHairService/GetCartsResponse")]
        HairPeaceWebsite.PeaceReference.userCart[] GetCarts(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHairService/GetCarts", ReplyAction="http://tempuri.org/IHairService/GetCartsResponse")]
        System.Threading.Tasks.Task<HairPeaceWebsite.PeaceReference.userCart[]> GetCartsAsync(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHairService/addToCart", ReplyAction="http://tempuri.org/IHairService/addToCartResponse")]
        bool addToCart(int userID, int ProdID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHairService/addToCart", ReplyAction="http://tempuri.org/IHairService/addToCartResponse")]
        System.Threading.Tasks.Task<bool> addToCartAsync(int userID, int ProdID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHairService/removeItem", ReplyAction="http://tempuri.org/IHairService/removeItemResponse")]
        bool removeItem(int userID, int ProdID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHairService/removeItem", ReplyAction="http://tempuri.org/IHairService/removeItemResponse")]
        System.Threading.Tasks.Task<bool> removeItemAsync(int userID, int ProdID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHairService/itemExists", ReplyAction="http://tempuri.org/IHairService/itemExistsResponse")]
        bool itemExists(int userID, int ProdID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHairService/itemExists", ReplyAction="http://tempuri.org/IHairService/itemExistsResponse")]
        System.Threading.Tasks.Task<bool> itemExistsAsync(int userID, int ProdID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHairService/getTotalItems", ReplyAction="http://tempuri.org/IHairService/getTotalItemsResponse")]
        int getTotalItems(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHairService/getTotalItems", ReplyAction="http://tempuri.org/IHairService/getTotalItemsResponse")]
        System.Threading.Tasks.Task<int> getTotalItemsAsync(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHairService/increasingQ", ReplyAction="http://tempuri.org/IHairService/increasingQResponse")]
        int increasingQ(int P_ID, int U_ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHairService/increasingQ", ReplyAction="http://tempuri.org/IHairService/increasingQResponse")]
        System.Threading.Tasks.Task<int> increasingQAsync(int P_ID, int U_ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHairService/decreasingQ", ReplyAction="http://tempuri.org/IHairService/decreasingQResponse")]
        int decreasingQ(int P_ID, int U_ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHairService/decreasingQ", ReplyAction="http://tempuri.org/IHairService/decreasingQResponse")]
        System.Threading.Tasks.Task<int> decreasingQAsync(int P_ID, int U_ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHairService/fillByDescOrder", ReplyAction="http://tempuri.org/IHairService/fillByDescOrderResponse")]
        HairPeaceWebsite.PeaceReference.Prod[] fillByDescOrder(int A);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHairService/fillByDescOrder", ReplyAction="http://tempuri.org/IHairService/fillByDescOrderResponse")]
        System.Threading.Tasks.Task<HairPeaceWebsite.PeaceReference.Prod[]> fillByDescOrderAsync(int A);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHairService/addDetails", ReplyAction="http://tempuri.org/IHairService/addDetailsResponse")]
        int addDetails(HairPeaceWebsite.PeaceReference.bDetails details);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHairService/addDetails", ReplyAction="http://tempuri.org/IHairService/addDetailsResponse")]
        System.Threading.Tasks.Task<int> addDetailsAsync(HairPeaceWebsite.PeaceReference.bDetails details);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHairService/AddTransaction", ReplyAction="http://tempuri.org/IHairService/AddTransactionResponse")]
        bool AddTransaction(HairPeaceWebsite.PeaceReference.tHistory transaction);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHairService/AddTransaction", ReplyAction="http://tempuri.org/IHairService/AddTransactionResponse")]
        System.Threading.Tasks.Task<bool> AddTransactionAsync(HairPeaceWebsite.PeaceReference.tHistory transaction);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHairService/ClearCart", ReplyAction="http://tempuri.org/IHairService/ClearCartResponse")]
        bool ClearCart(int UserID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHairService/ClearCart", ReplyAction="http://tempuri.org/IHairService/ClearCartResponse")]
        System.Threading.Tasks.Task<bool> ClearCartAsync(int UserID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHairService/getInvoice", ReplyAction="http://tempuri.org/IHairService/getInvoiceResponse")]
        HairPeaceWebsite.PeaceReference.tHistory[] getInvoice(int order);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHairService/getInvoice", ReplyAction="http://tempuri.org/IHairService/getInvoiceResponse")]
        System.Threading.Tasks.Task<HairPeaceWebsite.PeaceReference.tHistory[]> getInvoiceAsync(int order);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHairService/OrderExists", ReplyAction="http://tempuri.org/IHairService/OrderExistsResponse")]
        bool OrderExists(int order);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHairService/OrderExists", ReplyAction="http://tempuri.org/IHairService/OrderExistsResponse")]
        System.Threading.Tasks.Task<bool> OrderExistsAsync(int order);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHairService/getInvoices", ReplyAction="http://tempuri.org/IHairService/getInvoicesResponse")]
        HairPeaceWebsite.PeaceReference.tHistory[] getInvoices(int UserID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHairService/getInvoices", ReplyAction="http://tempuri.org/IHairService/getInvoicesResponse")]
        System.Threading.Tasks.Task<HairPeaceWebsite.PeaceReference.tHistory[]> getInvoicesAsync(int UserID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHairService/getAllInvoices", ReplyAction="http://tempuri.org/IHairService/getAllInvoicesResponse")]
        HairPeaceWebsite.PeaceReference.tHistory[] getAllInvoices();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHairService/getAllInvoices", ReplyAction="http://tempuri.org/IHairService/getAllInvoicesResponse")]
        System.Threading.Tasks.Task<HairPeaceWebsite.PeaceReference.tHistory[]> getAllInvoicesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHairService/getBillDetail", ReplyAction="http://tempuri.org/IHairService/getBillDetailResponse")]
        HairPeaceWebsite.PeaceReference.bDetails getBillDetail(int order);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHairService/getBillDetail", ReplyAction="http://tempuri.org/IHairService/getBillDetailResponse")]
        System.Threading.Tasks.Task<HairPeaceWebsite.PeaceReference.bDetails> getBillDetailAsync(int order);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHairService/UserLoggings", ReplyAction="http://tempuri.org/IHairService/UserLoggingsResponse")]
        void UserLoggings(int UserID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHairService/UserLoggings", ReplyAction="http://tempuri.org/IHairService/UserLoggingsResponse")]
        System.Threading.Tasks.Task UserLoggingsAsync(int UserID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHairService/pStakerSetup", ReplyAction="http://tempuri.org/IHairService/pStakerSetupResponse")]
        void pStakerSetup(int productID, int productQuantity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHairService/pStakerSetup", ReplyAction="http://tempuri.org/IHairService/pStakerSetupResponse")]
        System.Threading.Tasks.Task pStakerSetupAsync(int productID, int productQuantity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHairService/ActiveUsers", ReplyAction="http://tempuri.org/IHairService/ActiveUsersResponse")]
        int ActiveUsers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHairService/ActiveUsers", ReplyAction="http://tempuri.org/IHairService/ActiveUsersResponse")]
        System.Threading.Tasks.Task<int> ActiveUsersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHairService/InactiveUsers", ReplyAction="http://tempuri.org/IHairService/InactiveUsersResponse")]
        int InactiveUsers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHairService/InactiveUsers", ReplyAction="http://tempuri.org/IHairService/InactiveUsersResponse")]
        System.Threading.Tasks.Task<int> InactiveUsersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHairService/getTracking", ReplyAction="http://tempuri.org/IHairService/getTrackingResponse")]
        HairPeaceWebsite.PeaceReference.PTracking[] getTracking();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHairService/getTracking", ReplyAction="http://tempuri.org/IHairService/getTrackingResponse")]
        System.Threading.Tasks.Task<HairPeaceWebsite.PeaceReference.PTracking[]> getTrackingAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHairService/IncrementTracking", ReplyAction="http://tempuri.org/IHairService/IncrementTrackingResponse")]
        void IncrementTracking(string pageName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHairService/IncrementTracking", ReplyAction="http://tempuri.org/IHairService/IncrementTrackingResponse")]
        System.Threading.Tasks.Task IncrementTrackingAsync(string pageName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHairService/Days", ReplyAction="http://tempuri.org/IHairService/DaysResponse")]
        HairPeaceWebsite.PeaceReference.cLogInDays[] Days();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHairService/Days", ReplyAction="http://tempuri.org/IHairService/DaysResponse")]
        System.Threading.Tasks.Task<HairPeaceWebsite.PeaceReference.cLogInDays[]> DaysAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHairService/TransactionTings", ReplyAction="http://tempuri.org/IHairService/TransactionTingsResponse")]
        void TransactionTings(int pID, int Qty);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHairService/TransactionTings", ReplyAction="http://tempuri.org/IHairService/TransactionTingsResponse")]
        System.Threading.Tasks.Task TransactionTingsAsync(int pID, int Qty);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHairService/ChangePassWord", ReplyAction="http://tempuri.org/IHairService/ChangePassWordResponse")]
        bool ChangePassWord(string email, string newPass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHairService/ChangePassWord", ReplyAction="http://tempuri.org/IHairService/ChangePassWordResponse")]
        System.Threading.Tasks.Task<bool> ChangePassWordAsync(string email, string newPass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHairService/DeactivateAccount", ReplyAction="http://tempuri.org/IHairService/DeactivateAccountResponse")]
        bool DeactivateAccount(string email, string newPass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHairService/DeactivateAccount", ReplyAction="http://tempuri.org/IHairService/DeactivateAccountResponse")]
        System.Threading.Tasks.Task<bool> DeactivateAccountAsync(string email, string newPass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHairService/Add", ReplyAction="http://tempuri.org/IHairService/AddResponse")]
        bool Add(HairPeaceWebsite.PeaceReference.order_Attendence attend);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHairService/Add", ReplyAction="http://tempuri.org/IHairService/AddResponse")]
        System.Threading.Tasks.Task<bool> AddAsync(HairPeaceWebsite.PeaceReference.order_Attendence attend);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHairService/changeStatus", ReplyAction="http://tempuri.org/IHairService/changeStatusResponse")]
        void changeStatus(int OrderID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHairService/changeStatus", ReplyAction="http://tempuri.org/IHairService/changeStatusResponse")]
        System.Threading.Tasks.Task changeStatusAsync(int OrderID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHairService/getA_Orders", ReplyAction="http://tempuri.org/IHairService/getA_OrdersResponse")]
        HairPeaceWebsite.PeaceReference.order_Attendence[] getA_Orders();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHairService/getA_Orders", ReplyAction="http://tempuri.org/IHairService/getA_OrdersResponse")]
        System.Threading.Tasks.Task<HairPeaceWebsite.PeaceReference.order_Attendence[]> getA_OrdersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHairService/getOrderDate", ReplyAction="http://tempuri.org/IHairService/getOrderDateResponse")]
        System.DateTime getOrderDate(int order);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHairService/getOrderDate", ReplyAction="http://tempuri.org/IHairService/getOrderDateResponse")]
        System.Threading.Tasks.Task<System.DateTime> getOrderDateAsync(int order);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHairService/getStatusOrders", ReplyAction="http://tempuri.org/IHairService/getStatusOrdersResponse")]
        HairPeaceWebsite.PeaceReference.order_Attendence[] getStatusOrders();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHairService/getStatusOrders", ReplyAction="http://tempuri.org/IHairService/getStatusOrdersResponse")]
        System.Threading.Tasks.Task<HairPeaceWebsite.PeaceReference.order_Attendence[]> getStatusOrdersAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IHairServiceChannel : HairPeaceWebsite.PeaceReference.IHairService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HairServiceClient : System.ServiceModel.ClientBase<HairPeaceWebsite.PeaceReference.IHairService>, HairPeaceWebsite.PeaceReference.IHairService {
        
        public HairServiceClient() {
        }
        
        public HairServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HairServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HairServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HairServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Prod(string ID, string Name) {
            return base.Channel.Prod(ID, Name);
        }
        
        public System.Threading.Tasks.Task<bool> ProdAsync(string ID, string Name) {
            return base.Channel.ProdAsync(ID, Name);
        }
        
        public int searchProdID(int ID) {
            return base.Channel.searchProdID(ID);
        }
        
        public System.Threading.Tasks.Task<int> searchProdIDAsync(int ID) {
            return base.Channel.searchProdIDAsync(ID);
        }
        
        public int searchProd(string SerialNumber) {
            return base.Channel.searchProd(SerialNumber);
        }
        
        public System.Threading.Tasks.Task<int> searchProdAsync(string SerialNumber) {
            return base.Channel.searchProdAsync(SerialNumber);
        }
        
        public HairPeaceWebsite.PeaceReference.Prod GetProd(int ID) {
            return base.Channel.GetProd(ID);
        }
        
        public System.Threading.Tasks.Task<HairPeaceWebsite.PeaceReference.Prod> GetProdAsync(int ID) {
            return base.Channel.GetProdAsync(ID);
        }
        
        public bool modifyProd(HairPeaceWebsite.PeaceReference.Prod product, int ID) {
            return base.Channel.modifyProd(product, ID);
        }
        
        public System.Threading.Tasks.Task<bool> modifyProdAsync(HairPeaceWebsite.PeaceReference.Prod product, int ID) {
            return base.Channel.modifyProdAsync(product, ID);
        }
        
        public bool newProd(string ID) {
            return base.Channel.newProd(ID);
        }
        
        public System.Threading.Tasks.Task<bool> newProdAsync(string ID) {
            return base.Channel.newProdAsync(ID);
        }
        
        public bool appendNewProduct(HairPeaceWebsite.PeaceReference.Prod p) {
            return base.Channel.appendNewProduct(p);
        }
        
        public System.Threading.Tasks.Task<bool> appendNewProductAsync(HairPeaceWebsite.PeaceReference.Prod p) {
            return base.Channel.appendNewProductAsync(p);
        }
        
        public bool Login(string Email, string Password) {
            return base.Channel.Login(Email, Password);
        }
        
        public System.Threading.Tasks.Task<bool> LoginAsync(string Email, string Password) {
            return base.Channel.LoginAsync(Email, Password);
        }
        
        public HairPeaceWebsite.PeaceReference.User GetUser(string Email, string Password) {
            return base.Channel.GetUser(Email, Password);
        }
        
        public System.Threading.Tasks.Task<HairPeaceWebsite.PeaceReference.User> GetUserAsync(string Email, string Password) {
            return base.Channel.GetUserAsync(Email, Password);
        }
        
        public bool SearchUser(string Email) {
            return base.Channel.SearchUser(Email);
        }
        
        public System.Threading.Tasks.Task<bool> SearchUserAsync(string Email) {
            return base.Channel.SearchUserAsync(Email);
        }
        
        public HairPeaceWebsite.PeaceReference.User GetAnonUser(string Email) {
            return base.Channel.GetAnonUser(Email);
        }
        
        public System.Threading.Tasks.Task<HairPeaceWebsite.PeaceReference.User> GetAnonUserAsync(string Email) {
            return base.Channel.GetAnonUserAsync(Email);
        }
        
        public int editUser(HairPeaceWebsite.PeaceReference.User u, string email) {
            return base.Channel.editUser(u, email);
        }
        
        public System.Threading.Tasks.Task<int> editUserAsync(HairPeaceWebsite.PeaceReference.User u, string email) {
            return base.Channel.editUserAsync(u, email);
        }
        
        public bool Registered(string Email, string Password) {
            return base.Channel.Registered(Email, Password);
        }
        
        public System.Threading.Tasks.Task<bool> RegisteredAsync(string Email, string Password) {
            return base.Channel.RegisteredAsync(Email, Password);
        }
        
        public int Register(HairPeaceWebsite.PeaceReference.User u) {
            return base.Channel.Register(u);
        }
        
        public System.Threading.Tasks.Task<int> RegisterAsync(HairPeaceWebsite.PeaceReference.User u) {
            return base.Channel.RegisterAsync(u);
        }
        
        public HairPeaceWebsite.PeaceReference.Prod[] prodList() {
            return base.Channel.prodList();
        }
        
        public System.Threading.Tasks.Task<HairPeaceWebsite.PeaceReference.Prod[]> prodListAsync() {
            return base.Channel.prodListAsync();
        }
        
        public HairPeaceWebsite.PeaceReference.Prod[] fillBySpecial() {
            return base.Channel.fillBySpecial();
        }
        
        public System.Threading.Tasks.Task<HairPeaceWebsite.PeaceReference.Prod[]> fillBySpecialAsync() {
            return base.Channel.fillBySpecialAsync();
        }
        
        public HairPeaceWebsite.PeaceReference.Prod[] fillByProdType(string type) {
            return base.Channel.fillByProdType(type);
        }
        
        public System.Threading.Tasks.Task<HairPeaceWebsite.PeaceReference.Prod[]> fillByProdTypeAsync(string type) {
            return base.Channel.fillByProdTypeAsync(type);
        }
        
        public HairPeaceWebsite.PeaceReference.Prod[] fillByPrice(int n) {
            return base.Channel.fillByPrice(n);
        }
        
        public System.Threading.Tasks.Task<HairPeaceWebsite.PeaceReference.Prod[]> fillByPriceAsync(int n) {
            return base.Channel.fillByPriceAsync(n);
        }
        
        public HairPeaceWebsite.PeaceReference.Prod[] fillByBrand(string bName) {
            return base.Channel.fillByBrand(bName);
        }
        
        public System.Threading.Tasks.Task<HairPeaceWebsite.PeaceReference.Prod[]> fillByBrandAsync(string bName) {
            return base.Channel.fillByBrandAsync(bName);
        }
        
        public string[] htmlBrandFilter() {
            return base.Channel.htmlBrandFilter();
        }
        
        public System.Threading.Tasks.Task<string[]> htmlBrandFilterAsync() {
            return base.Channel.htmlBrandFilterAsync();
        }
        
        public HairPeaceWebsite.PeaceReference.userCart[] GetCarts(int userId) {
            return base.Channel.GetCarts(userId);
        }
        
        public System.Threading.Tasks.Task<HairPeaceWebsite.PeaceReference.userCart[]> GetCartsAsync(int userId) {
            return base.Channel.GetCartsAsync(userId);
        }
        
        public bool addToCart(int userID, int ProdID) {
            return base.Channel.addToCart(userID, ProdID);
        }
        
        public System.Threading.Tasks.Task<bool> addToCartAsync(int userID, int ProdID) {
            return base.Channel.addToCartAsync(userID, ProdID);
        }
        
        public bool removeItem(int userID, int ProdID) {
            return base.Channel.removeItem(userID, ProdID);
        }
        
        public System.Threading.Tasks.Task<bool> removeItemAsync(int userID, int ProdID) {
            return base.Channel.removeItemAsync(userID, ProdID);
        }
        
        public bool itemExists(int userID, int ProdID) {
            return base.Channel.itemExists(userID, ProdID);
        }
        
        public System.Threading.Tasks.Task<bool> itemExistsAsync(int userID, int ProdID) {
            return base.Channel.itemExistsAsync(userID, ProdID);
        }
        
        public int getTotalItems(int userId) {
            return base.Channel.getTotalItems(userId);
        }
        
        public System.Threading.Tasks.Task<int> getTotalItemsAsync(int userId) {
            return base.Channel.getTotalItemsAsync(userId);
        }
        
        public int increasingQ(int P_ID, int U_ID) {
            return base.Channel.increasingQ(P_ID, U_ID);
        }
        
        public System.Threading.Tasks.Task<int> increasingQAsync(int P_ID, int U_ID) {
            return base.Channel.increasingQAsync(P_ID, U_ID);
        }
        
        public int decreasingQ(int P_ID, int U_ID) {
            return base.Channel.decreasingQ(P_ID, U_ID);
        }
        
        public System.Threading.Tasks.Task<int> decreasingQAsync(int P_ID, int U_ID) {
            return base.Channel.decreasingQAsync(P_ID, U_ID);
        }
        
        public HairPeaceWebsite.PeaceReference.Prod[] fillByDescOrder(int A) {
            return base.Channel.fillByDescOrder(A);
        }
        
        public System.Threading.Tasks.Task<HairPeaceWebsite.PeaceReference.Prod[]> fillByDescOrderAsync(int A) {
            return base.Channel.fillByDescOrderAsync(A);
        }
        
        public int addDetails(HairPeaceWebsite.PeaceReference.bDetails details) {
            return base.Channel.addDetails(details);
        }
        
        public System.Threading.Tasks.Task<int> addDetailsAsync(HairPeaceWebsite.PeaceReference.bDetails details) {
            return base.Channel.addDetailsAsync(details);
        }
        
        public bool AddTransaction(HairPeaceWebsite.PeaceReference.tHistory transaction) {
            return base.Channel.AddTransaction(transaction);
        }
        
        public System.Threading.Tasks.Task<bool> AddTransactionAsync(HairPeaceWebsite.PeaceReference.tHistory transaction) {
            return base.Channel.AddTransactionAsync(transaction);
        }
        
        public bool ClearCart(int UserID) {
            return base.Channel.ClearCart(UserID);
        }
        
        public System.Threading.Tasks.Task<bool> ClearCartAsync(int UserID) {
            return base.Channel.ClearCartAsync(UserID);
        }
        
        public HairPeaceWebsite.PeaceReference.tHistory[] getInvoice(int order) {
            return base.Channel.getInvoice(order);
        }
        
        public System.Threading.Tasks.Task<HairPeaceWebsite.PeaceReference.tHistory[]> getInvoiceAsync(int order) {
            return base.Channel.getInvoiceAsync(order);
        }
        
        public bool OrderExists(int order) {
            return base.Channel.OrderExists(order);
        }
        
        public System.Threading.Tasks.Task<bool> OrderExistsAsync(int order) {
            return base.Channel.OrderExistsAsync(order);
        }
        
        public HairPeaceWebsite.PeaceReference.tHistory[] getInvoices(int UserID) {
            return base.Channel.getInvoices(UserID);
        }
        
        public System.Threading.Tasks.Task<HairPeaceWebsite.PeaceReference.tHistory[]> getInvoicesAsync(int UserID) {
            return base.Channel.getInvoicesAsync(UserID);
        }
        
        public HairPeaceWebsite.PeaceReference.tHistory[] getAllInvoices() {
            return base.Channel.getAllInvoices();
        }
        
        public System.Threading.Tasks.Task<HairPeaceWebsite.PeaceReference.tHistory[]> getAllInvoicesAsync() {
            return base.Channel.getAllInvoicesAsync();
        }
        
        public HairPeaceWebsite.PeaceReference.bDetails getBillDetail(int order) {
            return base.Channel.getBillDetail(order);
        }
        
        public System.Threading.Tasks.Task<HairPeaceWebsite.PeaceReference.bDetails> getBillDetailAsync(int order) {
            return base.Channel.getBillDetailAsync(order);
        }
        
        public void UserLoggings(int UserID) {
            base.Channel.UserLoggings(UserID);
        }
        
        public System.Threading.Tasks.Task UserLoggingsAsync(int UserID) {
            return base.Channel.UserLoggingsAsync(UserID);
        }
        
        public void pStakerSetup(int productID, int productQuantity) {
            base.Channel.pStakerSetup(productID, productQuantity);
        }
        
        public System.Threading.Tasks.Task pStakerSetupAsync(int productID, int productQuantity) {
            return base.Channel.pStakerSetupAsync(productID, productQuantity);
        }
        
        public int ActiveUsers() {
            return base.Channel.ActiveUsers();
        }
        
        public System.Threading.Tasks.Task<int> ActiveUsersAsync() {
            return base.Channel.ActiveUsersAsync();
        }
        
        public int InactiveUsers() {
            return base.Channel.InactiveUsers();
        }
        
        public System.Threading.Tasks.Task<int> InactiveUsersAsync() {
            return base.Channel.InactiveUsersAsync();
        }
        
        public HairPeaceWebsite.PeaceReference.PTracking[] getTracking() {
            return base.Channel.getTracking();
        }
        
        public System.Threading.Tasks.Task<HairPeaceWebsite.PeaceReference.PTracking[]> getTrackingAsync() {
            return base.Channel.getTrackingAsync();
        }
        
        public void IncrementTracking(string pageName) {
            base.Channel.IncrementTracking(pageName);
        }
        
        public System.Threading.Tasks.Task IncrementTrackingAsync(string pageName) {
            return base.Channel.IncrementTrackingAsync(pageName);
        }
        
        public HairPeaceWebsite.PeaceReference.cLogInDays[] Days() {
            return base.Channel.Days();
        }
        
        public System.Threading.Tasks.Task<HairPeaceWebsite.PeaceReference.cLogInDays[]> DaysAsync() {
            return base.Channel.DaysAsync();
        }
        
        public void TransactionTings(int pID, int Qty) {
            base.Channel.TransactionTings(pID, Qty);
        }
        
        public System.Threading.Tasks.Task TransactionTingsAsync(int pID, int Qty) {
            return base.Channel.TransactionTingsAsync(pID, Qty);
        }
        
        public bool ChangePassWord(string email, string newPass) {
            return base.Channel.ChangePassWord(email, newPass);
        }
        
        public System.Threading.Tasks.Task<bool> ChangePassWordAsync(string email, string newPass) {
            return base.Channel.ChangePassWordAsync(email, newPass);
        }
        
        public bool DeactivateAccount(string email, string newPass) {
            return base.Channel.DeactivateAccount(email, newPass);
        }
        
        public System.Threading.Tasks.Task<bool> DeactivateAccountAsync(string email, string newPass) {
            return base.Channel.DeactivateAccountAsync(email, newPass);
        }
        
        public bool Add(HairPeaceWebsite.PeaceReference.order_Attendence attend) {
            return base.Channel.Add(attend);
        }
        
        public System.Threading.Tasks.Task<bool> AddAsync(HairPeaceWebsite.PeaceReference.order_Attendence attend) {
            return base.Channel.AddAsync(attend);
        }
        
        public void changeStatus(int OrderID) {
            base.Channel.changeStatus(OrderID);
        }
        
        public System.Threading.Tasks.Task changeStatusAsync(int OrderID) {
            return base.Channel.changeStatusAsync(OrderID);
        }
        
        public HairPeaceWebsite.PeaceReference.order_Attendence[] getA_Orders() {
            return base.Channel.getA_Orders();
        }
        
        public System.Threading.Tasks.Task<HairPeaceWebsite.PeaceReference.order_Attendence[]> getA_OrdersAsync() {
            return base.Channel.getA_OrdersAsync();
        }
        
        public System.DateTime getOrderDate(int order) {
            return base.Channel.getOrderDate(order);
        }
        
        public System.Threading.Tasks.Task<System.DateTime> getOrderDateAsync(int order) {
            return base.Channel.getOrderDateAsync(order);
        }
        
        public HairPeaceWebsite.PeaceReference.order_Attendence[] getStatusOrders() {
            return base.Channel.getStatusOrders();
        }
        
        public System.Threading.Tasks.Task<HairPeaceWebsite.PeaceReference.order_Attendence[]> getStatusOrdersAsync() {
            return base.Channel.getStatusOrdersAsync();
        }
    }
}
